// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcJ5_185v8aHaR5XK_5ApP6kn6ReyAr2I',
    appId: '1:767681400570:web:a7c2c6afa56968a1ef8343',
    messagingSenderId: '767681400570',
    projectId: 'something-unique-abd05',
    authDomain: 'something-unique-abd05.firebaseapp.com',
    storageBucket: 'something-unique-abd05.firebasestorage.app',
    measurementId: 'G-DD5NZ0Y5V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7WfRon9pl9o2EK3Zy8e0de_7q3tOH9gM',
    appId: '1:767681400570:android:3740567252d13207ef8343',
    messagingSenderId: '767681400570',
    projectId: 'something-unique-abd05',
    storageBucket: 'something-unique-abd05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_YYNJhFlagMusERxVuWSS18fGBbWbvqs',
    appId: '1:767681400570:ios:485d048d72d7c10bef8343',
    messagingSenderId: '767681400570',
    projectId: 'something-unique-abd05',
    storageBucket: 'something-unique-abd05.firebasestorage.app',
    iosBundleId: 'com.example.mimiqit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_YYNJhFlagMusERxVuWSS18fGBbWbvqs',
    appId: '1:767681400570:ios:485d048d72d7c10bef8343',
    messagingSenderId: '767681400570',
    projectId: 'something-unique-abd05',
    storageBucket: 'something-unique-abd05.firebasestorage.app',
    iosBundleId: 'com.example.mimiqit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcJ5_185v8aHaR5XK_5ApP6kn6ReyAr2I',
    appId: '1:767681400570:web:f46b3e076d3deb35ef8343',
    messagingSenderId: '767681400570',
    projectId: 'something-unique-abd05',
    authDomain: 'something-unique-abd05.firebaseapp.com',
    storageBucket: 'something-unique-abd05.firebasestorage.app',
    measurementId: 'G-4QWF79JY8N',
  );
}
